### PR TITLE
Allow use in application extensions

### PR DESCRIPTION
**Pull request by simonboots**
In order to safely use KZPropertyMapper in application extensions, APPLICATION_EXTENSION_API_ONLY needs to be set to YES. This does not have any effect on non-extension bundles.

### CODE REVIEW

**Comment by glaszig** [comment]
KZPropertyMapper?

**Comment by simonboots** [comment]
Sorry, I meant SZTextView. I raised a similar PR for KZPropertyMapper and must have made a copy and paste mistake.

**Comment by simonboots** [comment]
Are you not interested in taking this change?

**Comment by glaszig** [comment]
potentially yes but i havent gotten around to understand the implications yet.

**Comment by simonboots** [comment]
Great, let me know if you have any questions.

**Comment by glaszig** [comment]
alright.

- are you using cocoapods?
- wouldn't it be better to have different targets for iOS and app extensions?
- apps which have this variable set to `NO` will still be able to link this library?

**Comment by simonboots** [comment]
> are you using cocoapods?

I am using Carthage

> wouldn't it be better to have different targets for iOS and app extensions?

If you're not using `UIApplication.shared` or any other APIs that aren't allowed in app extensions, I don't think this is necessary. Once you start using one of those APIs (Xcode will tell you) you can always create another target. But until then, it would only make clients have to ship your framework twice (with the same binary). There is no benefit to it (yet).

> apps which have this variable set to NO will still be able to link this library?

Yes, of course. Non-extension bundles can still link against and use the library. This flag purely indicates that this framework is safe to use in extensions. It has no effect when used in regular applications.

**Comment by glaszig** [comment]
sounds reasonable. thanks a bunch.

**Pull request merged**
