### PR TITLE
fading placeholder

### PR DESCRIPTION
**Pull request by jaropawlak**
I've added ability to fade placeholder (also configurable in designer)

### CODE REVIEW

**Comment by glaszig** [comment]
doesn't work in the simulator (with the supplied demo app).

**Comment by jaropawlak** [comment]
ah, I had a bug when app started with text present in textview. That is why I didn't notice it earlier (I start with empty textView). First check if placeholder should be visible was before fadeTime was set and default behavior was used (which removed placeholder from view). Later changes of placeholder visibility (when fadeTime was already set) didn't matter as placeholder was not in view anymore. I have committed a fix for that which works in demo app too. Thank you.

**Comment by glaszig** [comment]
appears to be working. a few things before i'll merge, please:

- put curly braces after `if`/`else` statements with one space, not below
- use dot-notation for property getters _and_ setters (`self.fadeTime`,  `self._placeholderTextView`, `object.alpha = 1`)
- put proper spaces between operators and operands (`self.fadeTime > 0.0`)
- remove trailing spaces
- squash all your commits into one

**Comment by jaropawlak** [comment]
done, thanks!

**Pull request merged**
